export const ONCHANGEQUERY = "ONCHANGEQUERY";
export const PRETTIFYQUERY = "PRETTIFYQUERY";
export const RUNRESULT = "RUNRESULT";
export const SETQUERYRESULT = "SETQUERYRESULT";
export const ADDMARKQUERY = "ADDMARKQUERY";
export const ONSETSIDEBAROPEN = "ONSETSIDEBAROPEN";
export const PINSIDEBAR = "PINSIDEBAR";
